# Generated by Django 5.1.4 on 2025-01-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_rename_favorite_tbfavorite_rename_product_tbproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbproduct',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
