# Generated by Django 5.1.4 on 2025-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_tbproduct_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbfavorite',
            old_name='period',
            new_name='cdperiod',
        ),
        migrations.RenameField(
            model_name='tbfavorite',
            old_name='id',
            new_name='cvid',
        ),
        migrations.RenameField(
            model_name='tbproduct',
            old_name='product_type',
            new_name='ccproducttype',
        ),
        migrations.RenameField(
            model_name='tbproduct',
            old_name='amount',
            new_name='cvamount',
        ),
        migrations.RenameField(
            model_name='tbproduct',
            old_name='id',
            new_name='cvid',
        ),
        migrations.RemoveField(
            model_name='tbproduct',
            name='description',
        ),
        migrations.AddField(
            model_name='tbproduct',
            name='ccdescription',
            field=models.CharField(default=3, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
