# Generated by Django 5.1.4 on 2024-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_tbuser_ccemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbuser',
            name='ccname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tbuser',
            name='ccpassword',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
