# Generated by Django 5.1.4 on 2024-12-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_tbuser_ccname_alter_tbuser_ccpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbusertype',
            name='ccdescription',
            field=models.CharField(max_length=45),
        ),
    ]
