# Generated by Django 5.1.4 on 2024-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_tbusertype_ccdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbusertype',
            name='ccdescription',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
