# Generated by Django 5.1.4 on 2024-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_tbusertype_ccdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbuser',
            name='ccname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='tbuser',
            name='ccpassword',
            field=models.CharField(max_length=256),
        ),
    ]
