image: docker:latest

variables:
  CODE_ENVIRONMENT: dev
  ENV_VAR: $DEV_ENV

services:
  - docker:dind

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      variables:
        CODE_ENVIRONMENT: prd
        ENV_VAR: $PRD_ENV
    - when: always

stages:
  - build_and_push
  - deploy

build_and_push_images:
  stage: build_and_push
  script:
    - ./build.sh $CODE_ENVIRONMENT $TOKEN
  only:
    - main
    - dev
  tags:
    - shared

deploy:
  stage: deploy
  image: ubuntu:latest
  tags:
    - shared
  script:
    - apt-get update && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo 'echo $SSH_PASSPHRASE' > ~/.ssh/tmp && chmod 700 ~/.ssh/tmp
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh/tmp ssh-add -
    - ssh-keyscan -v -H $HOST_SERVER >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$ENV_VAR" > .env
    - ./deploy.sh $HOST_SERVER $CODE_ENVIRONMENT $TOKEN
  only:
    - main
    # - dev
