# Generated by Django 5.1.4 on 2025-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_rename_cv_id_association_cvid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cvvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
