# Generated by Django 5.1.4 on 2024-12-21 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cvid', models.AutoField(primary_key=True, serialize=False)),
                ('cvname', models.CharField(max_length=100)),
                ('cvemail', models.CharField(max_length=100)),
                ('cvbalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('cvcreatedate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('cvid', models.AutoField(primary_key=True, serialize=False)),
                ('cvscheduleid', models.IntegerField()),
                ('cvdaysdelayed', models.IntegerField(default=0)),
                ('cbpayed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerChargeLog',
            fields=[
                ('cvid', models.AutoField(primary_key=True, serialize=False)),
                ('cvvalue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cvcreatedate', models.DateTimeField(auto_now_add=True)),
                ('cvidcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer')),
            ],
        ),
    ]
