# Generated by Django 5.1.4 on 2024-12-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_rename_cvemail_customer_ccemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ccname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
