# Generated by Django 5.1.4 on 2024-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_alter_customer_ccname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ccemail',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ccname',
            field=models.CharField(max_length=100),
        ),
    ]
