# Generated by Django 5.1.3 on 2024-11-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('cc_message', models.CharField(max_length=50)),
                ('cv_schedule_id', models.IntegerField()),
                ('cd_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
