# Generated by Django 5.1.4 on 2025-01-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='cc_message',
            new_name='ccmessage',
        ),
        migrations.RenameField(
            model_name='trigger',
            old_name='cd_create_date',
            new_name='cdcreatedate',
        ),
        migrations.RenameField(
            model_name='trigger',
            old_name='cv_id',
            new_name='cvid',
        ),
        migrations.RenameField(
            model_name='trigger',
            old_name='cv_schedule_id',
            new_name='cvscheduleid',
        ),
    ]
